### ISSUE TITLE
Error whilst executing cmake command to reproduce results in local vagrant box

### ISSUE THREAD

**Issue by spikerheado1234** [CXWorks/alda-analysis#1]
I am running ubuntu 18.04 in a vagrant vm.

I have installed all the pre-requisite commands as stipulated in your AE. 

However, I am trying to build your project, alda-analysis. The steps I took to do this is:

`git clone https://github.com/CXWorks/alda-analysis.git` into my home folder (~)
`mv alda-anlaysis auto-analysis`
`cd auto-analysis` 
`mkdir build && cd build`
`cmake ../`

However, the following error pops up in the cmake process:
```
CMake Error at G-parser/CMakeLists.txt:24 (add_executable):
  Cannot find source file:

    parser.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at /usr/lib/llvm-6.0/lib/cmake/llvm/AddLLVM.cmake:436 (add_library):
  Cannot find source file:

    opt_gen.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  /usr/lib/llvm-6.0/lib/cmake/llvm/AddLLVM.cmake:659 (llvm_add_library)
  pass/CMakeLists.txt:24 (add_llvm_loadable_module)


CMake Error at rtLib/CMakeLists.txt:15 (add_library):
  Cannot find source file:

    cxx_gen.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: G_parser
CMake Error: Cannot determine link language for target "G_parser".
CMake Error: CMake can not determine linker language for target: eraser
CMake Error: Cannot determine link language for target "eraser".
CMake Error: Cannot determine link language for target "rtLibGen".
CMake Error: CMake can not determine linker language for target: rtLibGen
```

I have looked at the folder G-Parsers, there is indeed no parser.hpp (only a parser.y). This is the same issue with the folder rtLib (there is no file cxx_gen.cpp).

Please do let me know if I am doing something incorrectly.

**Comment by CXWorks** [comment]
Hi @spikerheado1234,

Thanks for your concern. You will need to use lex & yacc to generate the parser.hpp and other files to make the cmake happy.

A quick way to do this would be:

after `cd auto-analysis`, run this script first: `./auto_run.sh msan 0` => let's say if you want to reuse my MSan analysis.

You can read all the `auto_run.sh` files on each folder to see how the files are being generated.

Then you can use cmake or even import this project into CLion.
